// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

var foo = "Hello";

console.log(foo);

function add(x, y) {
  return x + y | 0;
}

function add2(param) {
  return 2 + param | 0;
}

console.log(add2(10));

console.log(3);

var my_coin = /* Quarter */[4];

var message;

if (typeof my_coin === "number") {
  switch (my_coin) {
    case 0 : 
        message = 0.1;
        break;
    case 1 : 
        message = 0.5;
        break;
    case 2 : 
        message = 0.01;
        break;
    
  }
} else {
  message = 4 * 0.25;
}

console.log(message);

var me = /* record */[
  /* age */5,
  /* name */"Big Reason"
];

exports.foo     = foo;
exports.add     = add;
exports.add2    = add2;
exports.my_coin = my_coin;
exports.message = message;
exports.me      = me;
/*  Not a pure module */
